name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FEX_VERSION: FEX-2311

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/fex-emu:latest
            ${{ secrets.DOCKER_USERNAME }}/fex-emu:${{ env.FEX_VERSION }}
          build-args: FEX_VERSION=${{ env.FEX_VERSION }}